language: cpp
install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update
  - sudo apt install build-essential libasound2-dev libgl1-mesa-dev pkg-config qt55base qt55svg
script:
  - if [ $CXX == g++ ]; then export QMAKE_SPEC=linux-g++; fi
  - if [ $CXX == clang++ ]; then export QMAKE_SPEC=linux-clang; fi
  - source /opt/qt55/bin/qt55-env.sh
  - qmake -spec $QMAKE_SPEC
  - make check

